POST http://localhost/aula/usuarios.php
Content-Type: application/json


{
    "nome": "Lima",
    "email": "lucas13342@email.com",
    "endereco": "Rua Exemplo, 123",
    "telefone": "11999555421",
    "senha": "323232"
    
}